### ISSUE TITLE
mapping bug

### ISSUE THREAD

**Issue by cxwx** [antonk52/bad-practices.nvim#6]
.../nvim/lazy/bad-practices.nvim/lua/bad_practices/hjkl.lua:39: E227: mapping already exists for w

# stacktrace:
  - /bad-practices.nvim/lua/bad_practices/hjkl.lua:39 _in_ **setup**
  - /bad-practices.nvim/lua/bad_practices/init.lua:38 _in_ **setup**
  - ~/cx_rc/config/nvim/init.lua:53
   Warn  17:28:39 notify.warn lazy.nvim # Config Change Detected. Reloading...

**Comment by antonk52** [comment]
Looks like we need to check for existing mappings before setting them. Do you want to send a pr?

**Comment by cxwx** [comment]
It's may keymap conflict with other plugins, I'm not sure how to solved
